---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ops.some.cn
  resources:
  - someapps
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ops.some.cn
  resources:
  - someapps/finalizers
  verbs:
  - update
- apiGroups:
  - ops.some.cn
  resources:
  - someapps/status
  verbs:
  - get
  - patch
  - update
