# permissions for end users to edit someapps.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: someapp-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: some-app-operator
    app.kubernetes.io/part-of: some-app-operator
    app.kubernetes.io/managed-by: kustomize
  name: someapp-editor-role
rules:
- apiGroups:
  - ops.some.cn
  resources:
  - someapps
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ops.some.cn
  resources:
  - someapps/status
  verbs:
  - get
