apiVersion: ops.some.cn/v1
kind: Someapp
metadata:
  name: nginx-test-canary-v2
spec:
  name: "nginx-test"
  type: "api"
  setHpa: "1->2"
  version: canary-v0.0.2
  enableIstio: true
  containers:
  - name: app
    image: nginx:alpine
    ports:
    - containerPort: 80
