apiVersion: ops.some.cn/v1
kind: Someapp
metadata:
  name: nginx-test
spec:
  appName: "nginx-test"
  appType: "api"
  hpaNums: "1->2"
  containers:
  - name: app
    image: nginx:alpine
    ports:
    - containerPort: 80
